version: '2'

services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    labels:
      kompose.service.type: nodeport
    ports:
      - '2181:2181'
    volumes:
      - 'zookeeper_data:/bitnami'
volumes:
  zookeeper_data:
    driver: local
